import {BookDetailsResponse, BooksResponse} from '@store/slices/bookSlice';

export const allBooksMock: BooksResponse = {
  data: [
    {
      id: '61c9c28fcc498b5c08845dd0',
      authors: ['Gúbio Moreira', 'Júlio César Macedo'],
      title: 'A veniam sint',
      pageCount: 1538,
      imageUrl: 'https://d2drtqy2ezsot0.cloudfront.net/Book-7.jpg',
      publisher: 'Nogueira - Barros',
      published: 2010,
    },
    {
      id: '61c9c28fcc498b5c08845d26',
      authors: ['Sara Carvalho', 'Meire Xavier'],
      title: 'Ab assumenda dolor',
      pageCount: 1743,
      imageUrl: 'https://d2drtqy2ezsot0.cloudfront.net/Book-6.jpg',
      publisher: 'Batista, Silva and Batista',
      published: 2020,
    },
    {
      id: '61c9c28fcc498b5c08845d06',
      authors: ['Sra. Ígor Oliveira', 'Marcelo Martins'],
      title: 'Accusantium nobis',
      pageCount: 298,
      imageUrl: 'https://d2drtqy2ezsot0.cloudfront.net/Book-3.jpg',
      publisher: 'Santos, Carvalho and Franco',
      published: 2013,
    },
    {
      id: '61c9c28fcc498b5c08845ce3',
      authors: ['Gustavo Carvalho'],
      title: 'Accusantium quisquam',
      pageCount: 831,
      imageUrl: 'https://d2drtqy2ezsot0.cloudfront.net/Book-3.jpg',
      publisher: 'Franco e Associados',
      published: 2020,
    },
    {
      id: '61c9c28fcc498b5c08845c55',
      authors: ['Lucas Saraiva', 'Margarida Costa Filho'],
      title: 'Accusantium sequi ad',
      pageCount: 484,
      imageUrl: 'https://d2drtqy2ezsot0.cloudfront.net/Book-1.jpg',
      publisher: 'Reis e Associados',
      published: 2021,
    },
    {
      id: '61c9c28fcc498b5c08845d66',
      authors: ['Felícia Melo'],
      title: 'Ad et',
      pageCount: 2053,
      imageUrl: 'https://d2drtqy2ezsot0.cloudfront.net/Book-5.jpg',
      publisher: 'Albuquerque - Albuquerque',
      published: 2021,
    },
    {
      id: '61c9c28fcc498b5c08845ced',
      authors: ['Alexandre Barros Neto'],
      title: 'Ad molestiae',
      pageCount: 907,
      imageUrl: 'https://d2drtqy2ezsot0.cloudfront.net/Book-7.jpg',
      publisher: 'Costa, Batista and Reis',
      published: 2015,
    },
    {
      id: '61c9c28fcc498b5c08845d04',
      authors: ['Lucas Saraiva', 'Srta. Lorraine Barros'],
      title: 'Adipisci',
      pageCount: 140,
      imageUrl: 'https://d2drtqy2ezsot0.cloudfront.net/Book-3.jpg',
      publisher: 'Silva, Franco and Moreira',
      published: 2010,
    },
    {
      id: '61c9c28fcc498b5c08845de5',
      authors: ['Ofélia Moraes', 'Dr. Ígor Souza', 'Fabrício Melo'],
      title: 'Alias',
      pageCount: 1073,
      imageUrl: 'https://d2drtqy2ezsot0.cloudfront.net/Book-9.jpg',
      publisher: 'Xavier LTDA',
      published: 2017,
    },
    {
      id: '61c9c28fcc498b5c08845d10',
      authors: ['Pablo Barros', 'Roberta Carvalho', 'Deneval Carvalho'],
      title: 'Alias consequatur',
      pageCount: 1403,
      imageUrl: 'https://d2drtqy2ezsot0.cloudfront.net/Book-5.jpg',
      publisher: 'Xavier - Carvalho',
      published: 2019,
    },
  ],
  page: 1,
  totalItems: 500,
  totalPages: 50,
};

export const detailsBookMock: BookDetailsResponse = {
  id: '1',
  title: 'Memórias Póstumas de Brás Cubas',
  authors: ['Machado de Assis'],
  imageUrl:
    'https://images-na.ssl-images-amazon.com/images/I/41ZS6DFo+vL._SX328_BO1,204,203,200_.jpg',
  pageCount: 159,
  publisher: 'Saraiva',
  published: 2019,
  category: 'romance',
  description:
    'A publicação desta obra não só inaugura o Realismo no Brasil, como inicia a etapa mais complexa da obra de Machado de Assis. Com ela, aprofunda-se a sua análise da realidade e refina-se a sua linguagem, sendo considerada a obra que prenuncia algumas técnicas da literatura moderna.',
  language: 'português',
  isbn10: '8502082191',
  isbn13: '978-8502082199',
};
